var field = new Field();
var fieldWrapper = document.getElementById("fieldWrapper");
fieldWrapper.style.width = (20 + Math.min(800, level.width * CELL_SIZE.width)) + "px";
fieldWrapper.style.height = (20 + Math.min(600, level.height * CELL_SIZE.height)) + "px";
level.player.level = getCookie("level", 1);
var programDiv = document.getElementById("program");
programDiv.style.width = fieldWrapper.style.width;
programDiv.style.height = 20 + 64;
loadAvailableCommands();
loadDragAndDrop();
initControls();
level.loadData();